#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Load ~/.aliases
if [[ -s "$HOME/.aliases" ]]; then
  source "$HOME/.aliases"
fi

# set up direnv
if (( $+commands[direnv] )) ; then
  eval "$(direnv hook zsh)"
fi

# set up FZF autocompletion and shell bindings
if [[ -f ~/.fzf.zsh ]]; then
  source ~/.fzf.zsh
elif [[ -f /usr/share/fzf/completion.zsh ]]; then
  source /usr/share/fzf/completion.zsh
else
  echo "fzf completion.zsh not found\n"
fi

if [[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ]]; then
  source /usr/share/doc/fzf/examples/key-bindings.zsh
elif [[ -f /usr/share/fzf/key-bindings.zsh ]]; then
  source /usr/share/fzf/key-bindings.zsh
else
  echo "fzf key-bindings.zsh not found\n"
fi

# For pass-git-helper
export GPG_TTY=$(tty)

# Source .zshrc.local if it exists
if [[ -s "$HOME/.zshrc.local" ]]; then
  source "$HOME/.zshrc.local"
fi

# For tmux-yank to work
bindkey -e

